# Setup
title:        Horários
tagline:      IFPB Campus Guarabira
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Moisés Guimarães
  url:        https://github.com/moisesguimaraes

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - csv_to_json.py
  - jekyll-cayman-theme.gemspec